name = "LdrMatrices"
uuid = "34324cfd-81a8-401b-8bbf-88ce3853c914"
authors = ["Nithin Govindarajan"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
